/**
 * Function to generate random no. between 10 to 99.
 * @returns - randomNumber - Random no. generated by random function between 10 to 99.
 */
function randomNumberGenerator() {
  return (randomNumber = Math.floor(Math.random() * (99 - 10 + 1)) + 10);
}
/**
 * sum - To calculate sum of generated random numbers. Initialized value 0
 */
var sum = 0;
/**
 * Method to generate and add five random numbers.
 * For i from 1 to 5 number = randomNumberGenerator().
 * Printing those random  numbers.
 * sum = sum + number.
 * @returns sum - sum of random integers.
 */
function sumOfRandoms() {
  for (i = 1; i <= 5; i++) {
    let number = randomNumberGenerator();
    console.log(number);
    sum += number;
  }
  return sum;
}
/**
 * Assigning sum to return of sumOfRandoms.
 */
sum = sumOfRandoms();
/**
 * Printing sum and average of the random numbers.
 */
console.log("Sum of Five random numbers: " + sum);
console.log("Average of these numbers: " + sum / 5);
